CREATE TABLE cars (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    make VARCHAR(40) NOT NULL DEFAULT 'Mercedes-Benz',
    model VARCHAR(60) NOT NULL,
    year SMALLINT UNSIGNED NULL,
    body_type VARCHAR(40) NULL,
    seats TINYINT UNSIGNED NOT NULL DEFAULT 5,
    transmission ENUM('automatic','manual') NOT NULL DEFAULT 'automatic',
    fuel_type ENUM('petrol','diesel','hybrid') NOT NULL DEFAULT 'petrol',
    registration_plate VARCHAR(20) NOT NULL,
    daily_price DECIMAL(10,2) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'KES',
    status ENUM('active','maintenance','retired') NOT NULL DEFAULT 'active',
    image_path VARCHAR(255) NULL,
    description TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_cars_plate (registration_plate),
    KEY idx_cars_status (status, deleted_at),
    KEY idx_cars_price (daily_price),
    CONSTRAINT chk_cars_price CHECK (daily_price >= 0),
    CONSTRAINT chk_cars_seats CHECK (seats BETWEEN 1 AND 20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
