CREATE TABLE bookings (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    booking_ref VARCHAR(20) NOT NULL,
    client_id INT UNSIGNED NOT NULL,
    car_id INT UNSIGNED NOT NULL,
    pickup_date DATE NOT NULL,
    return_date DATE NOT NULL,
    actual_return_at DATETIME NULL,
    daily_rate DECIMAL(10,2) NOT NULL,
    total_amount DECIMAL(12,2) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'KES',
    status ENUM('pending_payment','confirmed','active','completed','cancelled','no_show')
        NOT NULL DEFAULT 'pending_payment',
    pickup_location VARCHAR(120) NULL,
    notes VARCHAR(500) NULL,
    created_by INT UNSIGNED NULL,
    cancelled_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_bookings_ref (booking_ref),
    KEY idx_bookings_client (client_id),
    KEY idx_bookings_car_dates (car_id, pickup_date, return_date),
    KEY idx_bookings_status (status),
    KEY idx_bookings_pickup (pickup_date),
    CONSTRAINT chk_bookings_dates CHECK (return_date > pickup_date),
    CONSTRAINT chk_bookings_amount CHECK (total_amount >= 0),
    CONSTRAINT fk_bookings_client FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE RESTRICT,
    CONSTRAINT fk_bookings_car FOREIGN KEY (car_id) REFERENCES cars (id) ON DELETE RESTRICT,
    CONSTRAINT fk_bookings_creator FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
