CREATE TABLE payments (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    booking_id INT UNSIGNED NOT NULL,
    client_id INT UNSIGNED NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'KES',
    method ENUM('mpesa','cash','bank_transfer','manual') NOT NULL DEFAULT 'mpesa',
    status ENUM('pending','confirmed','failed','refunded') NOT NULL DEFAULT 'pending',
    mpesa_receipt VARCHAR(20) NULL,
    mpesa_phone VARCHAR(20) NULL,
    checkout_request_id VARCHAR(100) NULL,
    merchant_request_id VARCHAR(100) NULL,
    confirmed_by INT UNSIGNED NULL,
    notes VARCHAR(255) NULL,
    paid_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_payments_receipt (mpesa_receipt),
    KEY idx_payments_booking (booking_id),
    KEY idx_payments_client (client_id),
    KEY idx_payments_status (status),
    KEY idx_payments_checkout (checkout_request_id),
    CONSTRAINT chk_payments_amount CHECK (amount > 0),
    CONSTRAINT fk_payments_booking FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE RESTRICT,
    CONSTRAINT fk_payments_client FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE RESTRICT,
    CONSTRAINT fk_payments_confirmer FOREIGN KEY (confirmed_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
